apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
        - name: devops-lab
          image: laith313/devops-lab:latest
          ports:
            - containerPort: 80
